#!/usr/bin/env python3
"""Bundle the content script.

`import()` inside a content script is checked against the HOST page's CSP, not
the extension's, so dynamic imports fail on any site with a strict policy --
i.e. most news sites, which is exactly the target. The modules stay ESM so the
parity tests can import them; this concatenates them with the export keywords
stripped and emits one classic script.

    python scripts/build_extension.py
"""
from __future__ import annotations
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXT = ROOT / "extension"
PARTS = ["lib/segment.js", "lib/proposer.js", "content.js"]
OUT = EXT / "content.bundle.js"


def strip_module_syntax(src: str) -> str:
    src = re.sub(r"^export\s+(?=(const|let|var|function|class))", "", src,
                 flags=re.MULTILINE)
    src = re.sub(r"^import\s.*?;\s*$", "", src, flags=re.MULTILINE | re.DOTALL)
    return src


def main() -> None:
    chunks = ["// GENERATED by scripts/build_extension.py -- do not edit.",
              "// Sources: " + ", ".join(PARTS), "(function () {", '"use strict";']
    for part in PARTS:
        chunks.append(f"\n// ---- {part} " + "-" * (60 - len(part)))
        chunks.append(strip_module_syntax((EXT / part).read_text()))
    chunks.append("})();")
    OUT.write_text("\n".join(chunks))
    print(f"[build] {OUT.relative_to(ROOT)}  {OUT.stat().st_size/1024:.1f} KB")

    import json
    mf = EXT / "manifest.json"
    m = json.loads(mf.read_text())
    m["content_scripts"][0]["js"] = ["content.bundle.js"]
    mf.write_text(json.dumps(m, indent=2) + "\n")
    print("[build] manifest -> content.bundle.js")


if __name__ == "__main__":
    main()
